### ISSUE TITLE
Parse error when using ! in rule files. 

### ISSUE THREAD

**Issue by newtux** [data-cleaning/validate#56]
The following works:

```r
> iris %>% check_that(!is.na(Sepal.Width)) %>% summary()
  rule items passes fails nNA error warning          expression
1   V1   150    150     0   0 FALSE   FALSE !is.na(Sepal.Width)
```
However when I put the same expression in a rule file, i.e.:

```yaml
# test rule

rules:
- 
  expr: !is.na(Sepal.Width)
  name: Test NA
  label: Test NA
  description: |
   Testing NA behavior
```

I get a parse error:

```r
> v <- validator(.file='~/test.yaml')
Error in parse(text = x$expr)[[1]] : subscript out of bounds
```

**Comment by markvanderloo** [comment]
This is because the exclamation mark is part of the yaml format. It tells the parser that a custom type is coming (for which one can specify handlers when calling the yaml parser).

The solution is to enquote the expression, i.e.

```
# test rule

rules:
- 
  expr: '!is.na(Sepal.Width)'
  name: Test NA
  label: Test NA
  description: |
    Testing NA behavior
```

Thanks for reporting, I will update the documentation accordingly.

Some day we should have a shiny app that facilitates setting up such files so no-one has to actually type in these yaml files.
